auth.tf, variables.tf
Some security improvements to the (Default) setup of CloudFront:
* Update the default TLS version to the (suggested) version [`TLSv1.1_2016`](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html#secure-connections-supported-ciphers).
* Changed the list of default allowed methods
* Added missing tags
=> [CBS-24] Set default Security Policy to TLSv1.1_2016 and tweak allowed methods

main.tf
As stated by the [documentation](https://www.terraform.io/docs/providers/aws/r/acm_certificate.html):
```
It's recommended to specify create_before_destroy = true in a lifecycle block to replace a certificate which is currently in use (eg, by aws_lb_listener).
```
Since the certificate is used by the CloudFront distribution, implement this
=> [IOT-438] Fix DNS change handing of certificate

main.tf, variables.tf
Terraform has the [`wait_for_deployment`](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#wait_for_deployment) option to specify if it should wait for the entire CloudFront distribution to be deployed.
When CloudFront updates, 2 things happen: The update itself is validated and processe, and then it deploys it globally over all edge locations. This second step can take up to 30 (updates) or 60 (creates) minutes.
The first step is the most important: is the new CloudFront Distribution configuration valid and correct.
For most (if not all) of the Terraform disployments this first step matters (exception could be a resource actually using the CloudFront endpoints). This PR makes this setting configurable and disables the wait by default.
=> Make "wait_for_deployment" configurable and disable by default

auth.tf, variables.tf
This PR adds the [`hide_ios`](https://www.terraform.io/docs/providers/okta/r/app_oauth.html#hide_ios) setting to the Okta app, this result in the following:
This makes it consistent with the other applications we configure in Okta
=> Add "hide_ios" option to the Okta app

main.tf
Add a dependency between the CloudFront Distribution and the Certificate Validation.
Hitting the 
```Error: error creating CloudFront Distribution: InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.```
error.
Added this dependency based on the information in the TF issue:
https://github.com/terraform-providers/terraform-provider-aws/issues/8945#issuecomment-582960043
=> Add dependency to the certificate validation

outputs.tf
Outputs don't exist when `authentication` is disabled
=> Fix optional outputs

auth.tf
Suppress the `consent_method` attribute that forces an update every run.
See also: https://github.com/oktadeveloper/terraform-provider-okta/issues/122
=> Ignore changes in Okta consent_method

main.tf
Rebuild the domain validation part (again), the current solution with the `for_each` ([introduced here](https://github.com/schubergphilis/terraform-aws-mcaf-cloudfront/pull/43/files) has issues when used in creating infrastructure from scratch, giving the classic error:
```
Error: Invalid for_each argument
on .terraform/modules/br001oc_cb_opco.tagmanager/main.tf line 43, in resource "aws_route53_record" "validation":
43:   for_each = {
44:     for dvo in aws_acm_certificate.default[0].domain_validation_options : dvo.domain_name => {
45:       name   = dvo.resource_record_name
46:       record = dvo.resource_record_value
47:       type   = dvo.resource_record_type
48:     }
49:   }
The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform …
```
=> Change Domain validation method

auth.tf
Instead of creating a custom KMS for every CloudFront, use the AWS managed key. This simplified the code and saves cost.
This will be a 2 PR (and release) process since it cannot be done in 1 PR for existing deployments:
- Using the AWS managed key by not specifying the KMS key does not work with updates (see: https://github.com/hashicorp/terraform-provider-aws/issues/20150)
- Removing the KMS key in the same PR kills the Terraform run (since the KMS will be destroyed first, after which the update of the SSM parameter fails).
So this is the first PR which updates the SSM values to use the AWS managed key.
=> Use AWS managed KMS key (1/2)

auth.tf
Instead of creating a custom KMS for every CloudFront, use the AWS managed key. This simplified the code and saves cost.
Part of 2, see also: https://github.com/schubergphilis/terraform-aws-mcaf-cloudfront/pull/78
If an existing CloudFront installation is already deployed there are 2 ways to migrate to the AWS managed key:
**Fully automated:** 
- Update to version `0.8.2` (from previous PR) as an intermediate to correct the SSM parameter values
- Then update to version `0.9.0` (This PR) to remove the old KMS key
**Semi automated**
- Manually remove the current SSM parameters from AWS
- Update to version `0.9.0` (This PR) to remove the old KMS key and recreate the SSM parameters with the correct (AWS managed) key
P.S.
This also fixes the "issue" that the KMS key was ALWAYS created, even if …
=> Use AWS managed KMS key (2/2)

auth.tf, variables.tf
Application logo can now be configured using Terraform (https://github.com/okta/terraform-provider-okta/issues/506). This PR implements this feature
=> Add Okta application logo support

README.md, auth.tf, bucket.tf
This PR refactors the way groups and users are ignore for Okta resources.
The current way of ignoring (lifecycle policies) has 2 issues:
- The "old" groups/users configurations are deprecated. E.g.  for `okta_group` the `users` attribute is deprecated and replaced with the `okta_group_memberships` resource. Same solution is applied to Apps.
- The Ignore lifecycle solution still calls the API for retrieving users and groups, having a negative impact on the rate limiting.
Apart from the new resources, "recently" a feature was implemented to complety skip the syncronisation of users and groups. This is handled by the `skip_users` and `skip_groups` attributes.
Implement this change to lower API usage and get rid of the deprecation warning (before they become errors).
Documentation:
* …
=> Fix Okta deprecation and bump modules

README.md, auth.tf, versions.tf
New version of the Okta Terraform provider is released: https://github.com/okta/terraform-provider-okta/blob/master/CHANGELOG.md#3360-september-14-2022
In this version the property `pkce_required ` is added which can give errors in specific situations:
```
Error: failed to update OAuth application: the API returned an error: Api validation failed: App Instance. Causes:
errorSummary: ''pkce_required'' must be set to true when ''token_endpoint_auth_method'' is ''none''.
```
This PR sets the `pkce_required` as well based on `okta_spa`
=> Add support for new property pkce_required

README.md, auth.tf, versions.tf
This PR refactors the Okta Group assignment from multiple resources into a single resource that uses a bulk endpoint.
This improves the amount of calls to Okta and prevents rate limiting issues.
**Documentation and links:**
- https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_group_assignments
- https://github.com/okta/terraform-provider-okta/issues/396
- https://github.com/okta/terraform-provider-okta/blob/master/CHANGELOG.md#3380-october-28-2022
When testing this a bit already had an implementation where the amount of resources go from 15 to 1
=> Optimize Okta Group Assignment

auth.tf
If no Okta groups are specified it gives an error:
```Error: Invalid dynamic for_each value
on xxx/auth.tf line 78, in resource "okta_app_group_assignments" "default":
for_each = toset(local.okta_groups)
local.okta_groups is null
Cannot use a null value in for_each.```
=> Handle "no Okta groups"

README.md, bucket.tf
Bump the S3 module to prevent breaking of new deployments.
See also: https://github.com/schubergphilis/terraform-aws-mcaf-s3/pull/26
=> Bump S3 module

auth.tf, variables.tf
This seem to fix a bug where it gets stuck. By default it is already not set, but setting it explicitly to null should fix the issue.
=> Set authentication policy explicitly to null for okta app

versions.tf
Bug that caused the previous issues with the V4 provider has been fixed, so moving back to it.
=> Support Okta V4 provider

README.md, bucket.tf, variables.tf
This PR adds support to configure the lifecycle rules of the S3 bucket. Which is handy since versioning is always enabled
=> Add support to configure the lifecycle policy of the origin bucket

main.tf
This PR changes the Route53 record from a CNAME to an Alias. 
Trusted advisor actually hinted on this
=> Change the DNS record to an ALIAS

.gitignore, README.md, variables.tf
Current Default TLS is 1.1, but should be at least 1.2:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html
The decision was made to choose `TLSv1.2_2018` as the latest, i.e. `TLSv1.2_2021 ` supports less Ciphers, see above link and could increase the change of bumping into breaking changes.
=> fix: [#118] Default TLS should be at least 1.2

auth.tf
**:hammer_and_wrench: Summary**
Add the `create_policy` to the Authentication Lambda. Needed else deployments fail (found while testing an upgrade from 0.X to 1.0
**:rocket: Motivation**
**:pencil: Additional Information**
=> fix: Add mandatory "create_policy" attribute

README.md, auth.tf, bucket.tf, examples/basic/terraform.tf, main.tf, terraform.tf, variables.tf
⚠️ **This introduces a breaking change as it requires at least v6 of the AWS provider.** ⚠️
This pull request updates the S3 Cloudfront Terraform module to support explicit region configuration and upgrades the AWS provider version. The main focus is on allowing users to specify the AWS region for (some) related resources, which improves multi-region compatibility and control. 
Since Cloudfront is a Global "fixed" region this region is now hardcoded inside the module, so no additional configuration is needed.
Additionally, some mcaf modules are updated, and the AWS provider version is updated to the latest major version.
**Region configuration improvements:** 
* Added a new `region` variable in `variables.tf` to allow users to specify the AWS region for the vpc and related resources. If …
=> feat!: Add region support 
